# DNS Update Configuration File

queuedir: queue
index: index.json

nameservers:
  - address: 10.0.0.1
    tsig:
      name: test-20230201.
      key: BA3V2qaseslfYlJ3+XGQwKgXPprlshGnJcFN9NxapNg=
      alg: hmac-sha256
  - address: 10.0.0.2
    tsig:
      name: test-20230201.
      key: BA3V2qaseslfYlJ3+XGQwKgXPprlshGnJcFN9NxapNg=
      alg: hmac-sha256
